export class Scholarship {
    applicants?: any[];
    city?: any;
    country?: any;
    criteria_info?: string;
    date_created?: string;
    deadline?: string;
    description?: string;
    education_field?: any;
    education_level?: any;
    eligible_schools?: any;
    extra_questions?: any;
    form_url?: string;
    funding_amount?: number;
    funding_type?: string[];
    id?: number;
    img_url?: any;
    is_automated?: boolean;
    metadata: any;
    name?: string;
    number_available_scholarships?: number;
    owner?: any;
    province?: any;
    purpose?: any;
    reference_letter_required?:number;
    resume_required?:any;
    scholarship_img_url?: string;
    scholarship_url?: string;
    slug?: string;
    submission_info?:any;
    transcript_required?:any;
  }
